paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
